import type { TBirdId } from './types_misc'

const BIRD_MAPPING: { [key in TBirdId]: string } = {
  0: 'Acorn Woodpecker',
  1: 'American Avocet',
  2: 'American Bittern',
  3: 'American Coot',
  4: 'American Crow',
  5: 'American Goldfinch',
  6: 'American Kestrel',
  7: 'American Oystercatcher',
  8: 'American Robin',
  9: 'American White Pelican',
  10: 'American Woodcock',
  11: 'Anhinga',
  12: "Anna's Hummingbird",
  13: 'Ash-Throated Flycatcher',
  14: 'Atlantic Puffin',
  15: "Baird's Sparrow",
  16: 'Bald Eagle',
  17: 'Baltimore Oriole',
  18: 'Barn Owl',
  19: 'Barn Swallow',
  20: 'Barred Owl',
  21: "Barrow's Goldeneye",
  22: "Bell's Vireo",
  23: 'Belted Kingfisher',
  24: "Bewick's Wren",
  25: 'Black Skimmer',
  26: 'Black Tern',
  27: 'Black Vulture',
  28: 'Black-Bellied Whistling Duck',
  29: 'Black-Billed Magpie',
  30: 'Black-Crowned Night-Heron',
  31: 'Black-Necked Stilt',
  32: 'Blue Grosbeak',
  33: 'Blue Jay',
  34: 'Blue-Gray Gnatcatcher',
  35: 'Blue-Winged Warbler',
  36: 'Bobolink',
  37: "Brewer's Blackbird",
  38: 'Bronzed Cowbird',
  39: 'Brown Pelican',
  40: 'Brown-Headed Cowbird',
  41: 'Burrowing Owl',
  42: 'Bushtit',
  43: 'California Condor',
  44: 'California Quail',
  45: 'Canada Goose',
  46: 'Carolina Chickadee',
  47: 'Carolina Wren',
  48: "Cassin's Finch",
  49: "Cassin's Sparrow",
  50: 'Cedar Waxwing',
  51: 'Cerulean Warbler',
  52: 'Chestnut-Collared Longspur',
  53: 'Chihuahuan Raven',
  54: 'Chimney Swift',
  55: 'Chipping Sparrow',
  56: "Clark's Grebe",
  57: "Clark's Nutcracker",
  58: 'Common Grackle',
  59: 'Common Loon',
  60: 'Common Merganser',
  61: 'Common Nighthawk',
  62: 'Common Raven',
  63: 'Common Yellowthroat',
  64: "Cooper's Hawk",
  65: 'Dark-Eyed Junco',
  66: 'Dickcissel',
  67: 'Double-Crested Cormorant',
  68: 'Downy Woodpecker',
  69: 'Eastern Bluebird',
  70: 'Eastern Kingbird',
  71: 'Eastern Phoebe',
  72: 'Eastern Screech Owl',
  73: 'Ferruginous Hawk',
  74: 'Fish Crow',
  75: "Forster's Tern",
  76: "Franklin's Gull",
  77: 'Golden Eagle',
  78: 'Grasshopper Sparrow',
  79: 'Gray Catbird',
  80: 'Great Blue Heron',
  81: 'Great Crested Flycatcher',
  82: 'Great Egret',
  83: 'Great Horned Owl',
  84: 'Greater Prairie Chicken',
  85: 'Greater Roadrunner',
  86: 'Green Heron',
  87: 'Hermit Thrush',
  88: 'Hooded Merganser',
  89: 'Hooded Warbler',
  90: 'Horned Lark',
  91: 'House Finch',
  92: 'House Wren',
  93: 'Inca Dove',
  94: 'Indigo Bunting',
  95: 'Juniper Titmouse',
  96: 'Killdeer',
  97: 'King Rail',
  98: 'Lazuli Bunting',
  99: "Lincoln's Sparrow",
  100: 'Loggerhead Shrike',
  101: 'Mallard',
  102: 'Mississippi Kite',
  103: 'Mountain Bluebird',
  104: 'Mountain Chickadee',
  105: 'Mourning Dove',
  106: 'Northern Bobwhite',
  107: 'Northern Cardinal',
  108: 'Northern Flicker',
  109: 'Northern Harrier',
  110: 'Northern Mockingbird',
  111: 'Northern Shoveler',
  112: 'Osprey',
  113: 'Painted Bunting',
  114: 'Peregrine Falcon',
  115: 'Pied-Billed Grebe',
  116: 'Pileated Woodpecker',
  117: 'Pine Siskin',
  118: 'Prothonotary Warbler',
  119: 'Purple Gallinule',
  120: 'Purple Martin',
  121: 'Pygmy Nuthatch',
  122: 'Red Crossbill',
  123: 'Red-Bellied Woodpecker',
  124: 'Red-Breasted Nuthatch',
  125: 'Red-Cockaded Woodpecker',
  126: 'Red-Eyed Vireo',
  127: 'Red-Headed Woodpecker',
  128: 'Red-Shouldered Hawk',
  129: 'Red-Tailed Hawk',
  130: 'Red-Winged Blackbird',
  131: 'Ring-Billed Gull',
  132: 'Rose-Breasted Grosbeak',
  133: 'Roseate Spoonbill',
  134: 'Ruby-Crowned Kinglet',
  135: 'Ruby-Throated Hummingbird',
  136: 'Ruddy Duck',
  137: 'Sandhill Crane',
  138: 'Savannah Sparrow',
  139: "Say's Phoebe",
  140: 'Scissor-Tailed Flycatcher',
  141: 'Snowy Egret',
  142: 'Song Sparrow',
  143: 'Spotted Owl',
  144: 'Spotted Sandpiper',
  145: 'Spotted Towhee',
  146: "Sprague's Pipit",
  147: "Steller's Jay",
  148: "Swainson's Hawk",
  149: 'Tree Swallow',
  150: 'Trumpeter Swan',
  151: 'Tufted Titmouse',
  152: 'Turkey Vulture',
  153: 'Violet-Green Swallow',
  154: 'Western Meadowlark',
  155: 'Western Tanager',
  156: 'White-Breasted Nuthatch',
  157: 'White-Crowned Sparrow',
  158: 'White-Faced Ibis',
  159: 'Whooping Crane',
  160: 'Wild Turkey',
  161: 'Willet',
  162: "Wilson's Snipe",
  163: 'Wood Duck',
  164: 'Wood Stork',
  165: 'Yellow-Bellied Sapsucker',
  166: 'Yellow-Billed Cuckoo',
  167: 'Yellow-Breasted Chat',
  168: 'Yellow-Headed Blackbird',
  169: 'Yellow-Rumped Warbler',
}

export default BIRD_MAPPING
